PERMISSION = 'You have no permission.'
NOTFOUND = 'No data found for this ID'
DELETED = 'Data deleted successfully.'
NO_CONTENT = 'Content Not found.'
USER_CREATED = 'User has been created successfully.'
USER_LOGIN = 'The user has been login successfully'
USER_LOGOUT = 'user has been logout'
